name = "omimaramadan"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LEADS"
id = "64d7dfca9968457baafbe8cace50eb78"
preview_id = "c4bda00cb15d4185bef06c530e0316cf"
